image:
  upload:
    save: /image/upload

server:
  error:
    whitelabel:
      enabled: false

  servlet:
    encoding:
      force-response: true

  port: 8080

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  session:
    store-type: redis

  redis:
    host: redis
    port: 6379

  profiles:
    active: init

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
    open-in-view: off

  web:
    resources:
      cache:
        period: 180


logging:
 level:
   root: info
   org.hibernate.SQL: debug
